Ability to split model components to different backend devices
leejet/stable-diffusion.cpp pull request #461
Opened 2024-11-14 04:15 UTC by softcookiepp

The ability to specify separate backend device indexes for CLIP, Unet, and VAE was implemented. This works for all backends that accept a device index as an initialization parameter (CUDA, Vulkan, and SYCL.) The aim of this was to support splitting the parts of the model across multiple GPUs.

2024-11-14 12:05 UTC, Green-Sky requested changes

2024-11-14 19:42 UTC, softcookiepp commented on stable-diffusion.cpp
> +				backend = ggml_backend_vk_init(device);
I copied this from the original code verbatim in order to ensure that behavior prior to my changes was preserved. Though if this is somehow an issue, I will fix it.

2024-11-15 21:36 UTC, softcookiepp commented
Everything should be fixed now

2024-11-20 14:55 UTC, Green-Sky requested changes

2024-11-20 14:55 UTC, Green-Sky commented on examples/cli/main.cpp
> +#include <stdexcept>
There are no exceptions used.

2024-11-20 22:51 UTC, softcookiepp commented on examples/cli/main.cpp
> +#include <stdexcept>
Done

2024-12-01 06:25 UTC, softcookiepp commented on examples/cli/main.cpp
> +#include <stdexcept>
Anything else that needs changing?

2026-05-25 02:26 UTC, closed without merging