vae tiling improvements: encoding support and adaptative overlap
leejet/stable-diffusion.cpp pull request #484
Opened 2024-11-26 15:12 UTC by stduhpf

- Added a boolean argument `sd_tiling()` function, specifying if the output tile is scaled up (for decoding) or if the input is (encoding). 
- Added a mechanism to automatically fix the tile overlaps in cases of mismatch between image size and tile size. 

With these changes, vae encoding can now be tiled, and a small (unreported?) issue with the upscaler (or tae) over-brightening some parts of the image is now fixed. This could also be a step toward tiled diffusion support. 

Fixes https://github.com/leejet/stable-diffusion.cpp/issues/588 and https://github.com/leejet/stable-diffusion.cpp/issues/564

2024-11-28 10:38 UTC, Green-Sky commented
>  * Added a mechanism to automatically fix the tile overlaps in cases of mismatch between image size and tile size.
> 
> 
> With these changes, vae encoding can now be tiled, and a small (unreported?) issue with the upscaler over-brightening some parts of the image is now fixed. This could also be a step toward tiled diffusion support.

Nice! It would also be interesting to see larger tile sizes. Depending on VAE, larger tiles would still fit into the memory budget and would speed things up.

2025-02-13 17:02 UTC, stduhpf commented
> The last_x used in the loop at [line 568](https://github.com/leejet/stable-diffusion.cpp/blob/d46ed5e184b97c2018dc2e8105925bdb8775e02c/ggml_extend.hpp#L568) (or line 629 in this PR) in ggml_extend.hpp is only initialized outside the loop.
Locally, it seems that this PR with initializing last_x = false; before the for (int x = 0; ~ loop would improve the generation results.

I'm sorry, I don't quite understand what you mean. `last_x` is already set to `false` when the loop starts.

> However, the brightness issue (issue https://github.com/leejet/stable-diffusion.cpp/issues/588) seems to remain.

You mean this PR doesn't fix it for you? If so this is strange, I can't reproduce the issue with this PR...

| master | PR |
| --- | --- | 
| ![tae_tiling_576](https://github.com/user-attachments/assets/117692c8-bf57-45bd-9940-e102dd17cc4a) | ![tae_tiling_576](https://github.com/user-attachments/assets/5da7513f-96a3-4372-887d-e0579c6feb25) |

As you can see the image made with the master branch is much brighter than the one with this PR.
 (ignore the slight variation of the composition, it's just a little unrelated bug of the vulkan backend that happens at non standard resolutions)

2025-02-15 13:32 UTC, stduhpf commented
> I think I have misled you, but there is no doubt that this PR is very good, as you have demonstrated in your examples. What I meant to say is that in your right cat PR image, for example, the position around the neck is slightly whiter than without vae-tiling; if it's a technical problem with the GGML backend or tiling (I usually use the vulkan backend), I'll find a better way.

The result with tiled VAE is always going to be slightly lower quality than the full VAE, because itt's lacking information about the whole image. When using TAE, the results are almost completely identical witth the PR, while on master, there is the "overexposure" issue on the tiled TAE.

2025-08-02 19:56 UTC, wbruna commented
@leejet , just to let you know: this PR has been included in Koboldcpp since a few releases ago (1.94 - 1.96.2) to fix #588, with no issues reported so far, so it should be safe to merge.

2025-09-06 12:05 UTC, wbruna commented
@stduhpf , would you please rebase this onto master? There are a few conflicts due to the VAE changes for Wan support.

2025-09-06 17:51 UTC, stduhpf commented
I haven't tested it, I know it builds fine, but I'm not sure if it actually works (I can't test it right now)

2025-09-06 18:13 UTC, wbruna commented
> I haven't tested it, I know it builds fine, but I'm not sure if it actually works (I can't test it right now)

No problem, I'll test it here.

2025-09-07 12:42 UTC, wbruna requested changes
I've only noticed a single, very familiar issue 😀

2025-09-07 12:42 UTC, wbruna commented on stable-diffusion.cpp
> +            get_vae_tile_sizes(tile_size_x, tile_size_y, tile_overlap, x->ne[0] / 8, x->ne[1] / 8);
This is on the decoding path, so it should be:

```c++
get_vae_tile_sizes(tile_size_x, tile_size_y, tile_overlap, x->ne[0], x->ne[1]);
```

2025-09-08 11:10 UTC, stduhpf commented
Encode is also broken, fixing it

2025-09-08 15:17 UTC, wbruna approved these changes
There is some unrelated whitespace changes, but apart from that it looks good to me. Working fine on with image to image in SDXL, SD3 and Chroma, and image edit with Kontext.

2025-09-10 14:00 UTC, leejet commented
Thank you for your contribution. Please change the environment variables to command-line arguments. Once this change is completed, I will merge the PR.

2025-09-10 15:19 UTC, wbruna commented
@leejet , a quick question: the VAE tiling doesn't really change the loaded models, and its usefulness depends on the chosen image resolution (we even have a workaround on Koboldcpp to enable or disable it at inference time). Could we move it, together with the new tiling size parameters, to the sd_img_gen_params_t struct (possibly a new sd_tiling_params_t struct)? (I can do this change, either separately or on top of this PR)

2025-09-10 18:09 UTC, leejet commented
> @leejet , a quick question: the VAE tiling doesn't really change the loaded models, and its usefulness depends on the chosen image resolution (we even have a workaround on Koboldcpp to enable or disable it at inference time). Could we move it, together with the new tiling size parameters, to the sd_img_gen_params_t struct (possibly a new sd_tiling_params_t struct)? (I can do this change, either separately or on top of this PR)

This is what I expect.

2025-09-10 20:46 UTC, stduhpf commented
> I can do this change, either separately or on top of this PR

@wbruna do you want to do these changes yourself or should I go ahead and start working on it?

2025-09-10 21:39 UTC, wbruna commented
> @wbruna do you want to do these changes yourself or should I go ahead and start working on it?

I won't be able to until Friday, so feel free to do it. From what I looked, the hardest part will be choosing how to implement the tile size parameters: that env var syntax kind of does too much 😃

2025-09-12 13:09 UTC, wbruna requested changes
Looking good, and working fine on a few tests. The only issue I notice was a crash on an invalid tile size (more detailed comments below).

2025-09-12 13:09 UTC, wbruna commented on stable-diffusion.h
> +    bool relative;
Perhaps this boolean could be dropped, and we apply the same logic as the command-line: if  `rel_size_ ` is bigger than 0.0, it overrides the `tile_size_` ?

2025-09-12 13:09 UTC, wbruna commented on stable-diffusion.cpp
> +            int tile_size_y    = vae_tiling_params.tile_size_y;
A relative size of 0.0 applies a 4x4 tile (doesn't look good, but works); but a zeroed-out tile size crashes. Maybe an invalid value could just mean the default?
```c++
int tile_size_x = vae_tiling_params.tile_size_x < 4 ? 32 : vae_tiling_params.tile_size_x;
int tile_size_y = vae_tiling_params.tile_size_y < 4 ? 32 : vae_tiling_params.tile_size_y;
```
Then we could also simplify the default values for the param struct, by using zeroed-out fields.

2025-09-12 13:18 UTC, wbruna commented on stable-diffusion.cpp
> +            int tile_size_y    = vae_tiling_params.tile_size_y;
Same issue with the tile_overlap above.

2025-09-12 13:47 UTC, stduhpf commented
Thanks for the review! I probably won't be able to work on these changes before tomorrow though.

2025-09-14 07:58 UTC, leejet commented
I think this PR can be merged now. Thank you all for your contributions.

2025-09-14 08:00 UTC, merged