stable-diffusion: TAESD implementation - faster autoencoder
leejet/stable-diffusion.cpp pull request #88
Opened 2023-11-26 17:33 UTC by FSSRepo

Fixes [#36](https://github.com/leejet/stable-diffusion.cpp/issues/36)

This is a quick implementation, so I may have overlooked something. Initially, I thought about implementing it in a separate header, but there were some issues due to dependencies collisions with ggml, and I honestly didn't want to bother solving that. Therefore, I directly added it to the `stable-diffusion.cpp` file.

I don't know why the quality degrades a bit, probably because the weights of the convolutions are in f16, there must be a slight drop in quality, or it must be inherent to the decoder model.

### Results

| Props | AutoEncoder KL | TinyAutoEncoder |
|--------------|--------------|--------------|
| Test 1  | ![output_akl](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/1276fa93-1139-4d9e-8b04-b58bcf41388c) |   ![output_taesd](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/7f7e32bc-04e8-4550-aef5-62df3aec5528) |
| Test 2   | ![output_kl](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/39e7de32-74a5-43c6-9763-41a271beae84)    | ![output_tae](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/d228529e-f0cf-4048-b170-b5e275cd6a7b)  |
| Processing Time (CPU Backend) | 24 seconds | 1.8 seconds |
| Params memory | 95 MB | 2 MB |
| Compute memory (512 x 512) | 1664 MB | 416 MB |

How to use it:

Just add `--taesd` to command line, just works for txt2img for now:

```bash
git clone https://github.com/FSSRepo/stable-diffusion.cpp.git
mkdir build
cd build
cmake ..
cmake --build . --config Release

sd -p "a lovely cat" --taesd
```

Tasks:

- [ ] Implement the unary operation `ggml_tanh` in CUDA, for full offloading support.
- [ ] Complete the implementation of the encoder and perform tests.

2023-11-26 20:28 UTC, Green-Sky commented
> just add --taesd to command line

is this added to the gguf?, if its replacing the normal vae, then this should be inferred from the gguf file.

2023-11-26 20:44 UTC, FSSRepo commented
@Green-Sky it's a separated model, I included `taesd-decoder.gguf` it should be in your working path.

2023-11-26 22:29 UTC, Green-Sky commented
testing with lcm 4 steps:
## taesd
![output](https://github.com/leejet/stable-diffusion.cpp/assets/2938071/d9f9bbc5-bb00-4430-bbe1-2892c38a71fb)
```
[INFO]  stable-diffusion.cpp:5430 - sampling completed, taking 17.13s
[INFO]  stable-diffusion.cpp:5448 - latent 1 decoded, taking 1.44s
```


## model vae
:warning:  produces invalid image file :warning:

2023-11-26 22:30 UTC, FSSRepo commented
I don't understand

2023-11-26 22:36 UTC, Green-Sky commented
> > ⚠️ produces invalid image file ⚠️
> 
> I don't understand

ok, running without taesd AND lcm lora AND eulerA sampler (so not lcm sampler) produces invalid files. running more tests...

2023-11-26 22:39 UTC, Green-Sky commented
### works:
`$ bin/sd -m ../models/epicphotogasm_lastUnicorn-f16.gguf --lora-model-dir ../models/loras/sd1-gguf/ -p "<lora:lcm-lora-sdv1-5:1>a lovely cat" --steps 4 --cfg-scale 1.0 --sampling-method lcm`
`$ bin/sd -m ../models/epicphotogasm_lastUnicorn-f16.gguf --lora-model-dir ../models/loras/sd1-gguf/ -p "<lora:lcm-lora-sdv1-5:1>a lovely cat" --steps 4 --cfg-scale 1.0 --sampling-method euler_a --taesd`

### fails:
`$ bin/sd -m ../models/epicphotogasm_lastUnicorn-f16.gguf --lora-model-dir ../models/loras/sd1-gguf/ -p "<lora:lcm-lora-sdv1-5:1>a lovely cat" --steps 4 --cfg-scale 1.0 --sampling-method euler_a`
`$ bin/sd -m ../models/epicphotogasm_lastUnicorn-f16.gguf --lora-model-dir ../models/loras/sd1-gguf/ -p "<lora:lcm-lora-sdv1-5:1>a lovely cat" --steps 4 --cfg-scale 1.0 --sampling-method euler`

2023-11-26 23:10 UTC, FSSRepo commented
@Green-Sky I have conducted some tests, and I am not getting any errors related to the regular VAE or the sampling.

2023-11-26 23:25 UTC, Green-Sky commented
using a different, non-lora-lcm model, it does not produce an invalid file
`$ bin/sd -m ./LCM_Dreamshaper_v7-f16.gguf -p "a lovely cat" --steps 4 --cfg-scale 1.0 --sampling-method euler_a`



> @Green-Sky I have conducted some tests, and I am not getting any errors related to the regular VAE or the sampling. Does `master` have this error?

yes, it appears this also happens on master.

2023-11-26 23:27 UTC, FSSRepo commented
yes, it appears this also happens on master.

With the last commit before the latest commit of master

2023-11-26 23:39 UTC, FSSRepo commented
```bash
build\bin\Release\sd -m kotosmix_v10-f16.gguf -p "<lora:Kana_Arima-10:0.9><lora:lcm-lora:1>beautiful anime girl, short hair, red hair, red eyes, realistic, masterpiece, azur lane, 4k, high quality" --sampling-method lcm --cfg-scale 1 --steps 5 -t 6 -s 424354
```

### AutoEncoderKL
![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/d91ffbe8-1b6f-4e6f-b688-0664ce9e9170)

### TAESD

![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/f552db60-2e6d-48bf-9f73-b2de517b462f)

This is definitely not an error. It is well known that LCM Lora only works with the LCM sampler; with another one, it starts to give results with degradation and malformations.

2023-11-26 23:40 UTC, Green-Sky commented
> > yes, it appears this also happens on master.
> 
> With the last commit before the latest commit of master

not sure that can be indicative, since that is pre gguf -> maybe different model file

---

on master with the seed 1337 (instead of 42) it actually crashes, so i ran it in debug
```
sd: /home/green/workspace/stable-diffusion.cpp/common/./stb_image_write.h:1226: unsigned char* stbi_write_png_to_mem(const unsigned char*, int, int, int, int, int*, const char*): Assertion `o == out + *out_len' failed.
Aborted (core dumped)
```

2023-11-27 00:04 UTC, Green-Sky commented
I switched back to this branch and now it works in release mode. BUT in debug, it triggers the assert(). ( @leejet there is a bug in master )

sorry for spamming unrelated comments in your taesd pr :eyes:

2023-11-27 00:12 UTC, FSSRepo commented
When I enable `Debug` i get:

```bash
Assertion failed: node->src[j]->backend == GGML_BACKEND_GPU, file C:\proyectos\stable-diffusion.cpp\ggml\src\ggml-cuda.cu, line 8738
```

Only when I use `--taesd`, but I already know why it happen.

2023-11-27 00:32 UTC, Jonathhhan commented
Wow, very fast. Maybe it would be nice, if it is possible to set the `.gguf` file path in `stable-diffusion.h` (like with the `lora` files)?

2023-11-27 01:45 UTC, FSSRepo commented
Now the TAE model should pass like this `--taesd TAE_MODEL_PATH`:

```bash
build\bin\Release\sd -m AnythingV5_v5PrtRE-f16.gguf --taesd taesd-model.gguf -p "<lora:Kana_Arima-10:0.9><lora:lcm-lora:1>beautiful anime girl, short hair, red hair, red eyes, realistic, masterpiece, azur lane, 4k, high quality" --sampling-method lcm --cfg-scale 1 --steps 5 -t 1 -s 424354
```

2023-11-27 14:58 UTC, FSSRepo commented
> > I tried passing the init_latent generated by the encoder directly to the decoder, and I get dark results.
> 
> Are you using the original python implementation?

I get poor results with my implementation; as such, I haven't conducted tests with the Python implementation.

2023-11-27 15:10 UTC, leejet commented
I suggest that you compare the original Python version to see if the problem is with the model itself or your implementation

2023-11-27 17:57 UTC, Amin456789 commented
having this working with lcm will be a huge speed boost, thanks!

2023-11-27 20:50 UTC, Green-Sky commented
@FSSRepo looks like it is supposed to work again.

2023-11-27 21:15 UTC, FSSRepo commented
@leejet s pull request is ready for review and merge; I've tested everything, and with the latest commit, I've resolved the issue #92.

2023-11-27 21:17 UTC, Green-Sky commented
@FSSRepo can you merge from master, to get my fix in?

2023-11-27 21:54 UTC, FSSRepo commented
| AutoEncoderKL | TAESD |
| ----- | --- |
| ![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/771b5490-ec39-4dce-be3b-29a289001ffa) | ![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/74e2f1fd-d4a8-4149-bcce-672950767bea) |

2023-11-27 21:56 UTC, Green-Sky commented
It crashes when you try to create an image of size 1024x1024, but that's also on master. (with and without taesd)

2023-11-27 22:00 UTC, FSSRepo commented
```bash
[DEBUG] stable-diffusion.cpp:2409 - diffusion compute buffer size: 8353.60 MB

CUDA error 2 at C:\proyectos\stable-diffusion.cpp\ggml\src\ggml-cuda.cu:8665: out of memory
```

2023-11-27 22:02 UTC, Green-Sky commented
taesd 768x768 LCM 4steps 1.0-cfg-scale cpu-12threads flash-attention:
![output](https://github.com/leejet/stable-diffusion.cpp/assets/2938071/a4e83f8c-acbd-478d-8ed4-bd965a9fffae)
`[INFO]  stable-diffusion.cpp:5476 - sampling completed, taking 49.41s`
`[INFO]  stable-diffusion.cpp:5498 - decode_first_stage completed, taking 3.26s`

<details><summary>Details</summary>

```
$ bin/sd -m ../models/epicphotogasm_lastUnicorn-f16.gguf --lora-model-dir ../models/loras/sd1-gguf/ -p "<lora:lcm-lora-sdv1-5:1>a lovely cat" --steps 4 --cfg-scale 1.0 --sampling-method lcm --taesd ../taesd-model.gguf -W 768 -H 768
[INFO]  stable-diffusion.cpp:4454 - Flash Attention enabled
[INFO]  stable-diffusion.cpp:4457 - loading model from '../models/epicphotogasm_lastUnicorn-f16.gguf'
[INFO]  stable-diffusion.cpp:4485 - Stable Diffusion 1.x | epicphotogasm_lastUnicorn.safetensors
[INFO]  stable-diffusion.cpp:4493 - model data type: f16
[INFO]  stable-diffusion.cpp:4659 - total memory buffer size = 1877.33MB (clip 236.18MB, unet 1641.16MB, vae 0.00MB)
[INFO]  stable-diffusion.cpp:4665 - loading model from '../models/epicphotogasm_lastUnicorn-f16.gguf' completed, taking 0.61s
[INFO]  stable-diffusion.cpp:4689 - running in eps-prediction mode
[INFO]  stable-diffusion.cpp:3936 - loading taesd from '../taesd-model.gguf'
[INFO]  stable-diffusion.cpp:4015 - taesd model loaded
[INFO]  stable-diffusion.cpp:4030 - loading LoRA from '../models/loras/sd1-gguf/lcm-lora-sdv1-5.gguf'
[INFO]  stable-diffusion.cpp:4056 - LoRA Type: regular | lcm-lora-sdv1-5.safetensors
[INFO]  stable-diffusion.cpp:4076 - LoRA data type: f16
[INFO]  stable-diffusion.cpp:4771 - lora 'lcm-lora-sdv1-5' applied, taking 5.69s
[INFO]  stable-diffusion.cpp:5422 - apply_loras completed, taking 5.69s
[INFO]  stable-diffusion.cpp:5451 - get_learned_condition completed, taking 108 ms
[INFO]  stable-diffusion.cpp:5461 - sampling using LCM method
[INFO]  stable-diffusion.cpp:5464 - generating image: 1/1
  |==================================================| 4/4 - 12.27s/it
[INFO]  stable-diffusion.cpp:5476 - sampling completed, taking 49.41s
[INFO]  stable-diffusion.cpp:5484 - generating 1 latent images completed, taking 49.51s
[INFO]  stable-diffusion.cpp:5486 - decoding 1 latents
[INFO]  stable-diffusion.cpp:5494 - latent 1 decoded, taking 3.26s
[INFO]  stable-diffusion.cpp:5498 - decode_first_stage completed, taking 3.26s
[INFO]  stable-diffusion.cpp:5503 - txt2img completed in 52.88s
save result image to 'output.png'
```

</details>

2023-11-27 22:04 UTC, Green-Sky commented
> With 1024 x 1024
> 
> ```shell
> [DEBUG] stable-diffusion.cpp:2409 - diffusion compute buffer size: 8353.60 MB
> 
> CUDA error 2 at C:\proyectos\stable-diffusion.cpp\ggml\src\ggml-cuda.cu:8665: out of memory
> ```

cpu 1024 x 1024
```
ggml_new_object: not enough space in the context's memory pool (needed 14897648, available 14680064)
Segmentation fault (core dumped)
```

2023-11-27 22:11 UTC, Green-Sky commented
> I can convert the Stable Video model to gguf

for me it fails to load, probably bc it wrongly detects SD1.x (instead of SD2.x , i think)

2023-11-27 22:15 UTC, FSSRepo commented
@Green-Sky That is definitely a limitation we have with the current implementation of Conv2D; im2col with large images triggers memory usage.I am thinking about implementing Winograd, which is more memory-efficient, at least I believe so, but I lack advanced knowledge.

2023-11-27 22:20 UTC, FSSRepo commented
@Green-Sky For 1024 x 1024 images, taesd requires splitting them into tiles of 512 x 512 to function properly, but honestly, at the moment, I don't feel like extending this pull request any further.

2023-11-27 22:24 UTC, Green-Sky commented
> @Green-Sky For 1024 x 1024 images, taesd requires splitting them into tiles of 512 x 512 to function properly, but honestly, at the moment, I don't feel like extending this pull request any further.

sure, no problem :) -- maybe add a warning or error, so it does not just segfaults...

---

also tried to run it on my gpu (rtx 2070 mobile), and its fast, like, very
```
$ sd -m models/epicphotogasm_lastUnicorn-f16.gguf --lora-model-dir models/loras/sd1-gguf/ -p "<lora:lcm-lora-sdv1-5:1>a lovely cat" --sampling-method lcm --steps 4 --cfg-scale 1.0 --taesd ./taesd-model.gguf
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5
[INFO]  stable-diffusion.cpp:4457 - loading model from 'models/epicphotogasm_lastUnicorn-f16.gguf'
[INFO]  stable-diffusion.cpp:4485 - Stable Diffusion 1.x | epicphotogasm_lastUnicorn.safetensors
[INFO]  stable-diffusion.cpp:4493 - model data type: f16
[INFO]  stable-diffusion.cpp:4659 - total memory buffer size = 1877.33MB (clip 236.18MB, unet 1641.16MB, vae 0.00MB)
[INFO]  stable-diffusion.cpp:4665 - loading model from 'models/epicphotogasm_lastUnicorn-f16.gguf' completed, taking 0.51s
[INFO]  stable-diffusion.cpp:4689 - running in eps-prediction mode
[INFO]  stable-diffusion.cpp:3936 - loading taesd from './taesd-model.gguf'
[INFO]  stable-diffusion.cpp:4015 - taesd model loaded
[INFO]  stable-diffusion.cpp:4030 - loading LoRA from 'models/loras/sd1-gguf/lcm-lora-sdv1-5.gguf'
[INFO]  stable-diffusion.cpp:4056 - LoRA Type: regular | lcm-lora-sdv1-5.safetensors
[INFO]  stable-diffusion.cpp:4076 - LoRA data type: f16
[INFO]  stable-diffusion.cpp:4771 - lora 'lcm-lora-sdv1-5' applied, taking 0.22s
[INFO]  stable-diffusion.cpp:5422 - apply_loras completed, taking 0.22s
[INFO]  stable-diffusion.cpp:5451 - get_learned_condition completed, taking 10 ms
[INFO]  stable-diffusion.cpp:5461 - sampling using LCM method
[INFO]  stable-diffusion.cpp:5464 - generating image: 1/1
  |==================================================| 4/4 - 1.75it/s
[INFO]  stable-diffusion.cpp:5476 - sampling completed, taking 2.31s
[INFO]  stable-diffusion.cpp:5484 - generating 1 latent images completed, taking 2.31s
[INFO]  stable-diffusion.cpp:5486 - decoding 1 latents
[INFO]  stable-diffusion.cpp:5494 - latent 1 decoded, taking 0.18s
[INFO]  stable-diffusion.cpp:5498 - decode_first_stage completed, taking 0.18s
[INFO]  stable-diffusion.cpp:5503 - txt2img completed in 2.50s
save result image to 'output.png'
```
---
I also noticed, how much faster the lora is loaded on gpu. On cpu it takes 5sec, while here on gpu its only 0.22sec

2023-11-27 22:30 UTC, Green-Sky commented
too bad TAESD hates faces...

![output](https://github.com/leejet/stable-diffusion.cpp/assets/2938071/be4546d6-3c7e-47ee-a431-a06c6c557c58)

2023-11-28 10:51 UTC, Green-Sky commented on stable-diffusion.cpp
> +    if(width >= 1024 || height >= 1024) { // 1024 x 1024 images
actually, one side 1024 seems to be fine.

2023-11-28 11:28 UTC, Green-Sky commented on stable-diffusion.cpp
> +    if(width >= 1024 || height >= 1024) { // 1024 x 1024 images
![output](https://github.com/leejet/stable-diffusion.cpp/assets/2938071/a9dc5911-1ce6-43c5-9920-955417712556)

2023-11-28 11:34 UTC, Green-Sky commented
| TAESD | normal |
|--------|--------|
| ![output](https://github.com/leejet/stable-diffusion.cpp/assets/2938071/783f286a-e1c9-4b4c-a277-9e255dc04895) | ![output](https://github.com/leejet/stable-diffusion.cpp/assets/2938071/3486a1ce-dfc9-49cf-8c59-56c35f69b2ab) |

2023-11-28 14:10 UTC, FSSRepo commented
| Props | AutoEncoderKL | TAESD |
| ---- | ----- | --- |
| Image | ![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/b1f1f54c-926f-4fcc-be8d-7500b676779f) | ![output](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/07b42a44-866e-477a-af98-fdd78ca06261) |
| Compute Time (CPU Backend) | 61 seconds | 4.2 segs |
| Memory Usage | 3328 MB | 832 MB |

2023-11-28 16:28 UTC, leejet commented
> @leejet I already fixed the encoder error; it was the way the image was converted to a tensor. The encoder expected values in the range [0, 1], but image_to_ggml_vec provided values in the range [-1, 1]. After making a commit with the changes, now, for some reason, it takes long time to process after you merged the @Green-Sky's PR.
> 
> ![Screenshot 2023-11-27 145712](https://private-user-images.githubusercontent.com/57494570/285994259-a39d050c-07c2-4425-b571-2d604f1d8825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODg5MzIsIm5iZiI6MTcwMTE4ODYzMiwicGF0aCI6Ii81NzQ5NDU3MC8yODU5OTQyNTktYTM5ZDA1MGMtMDdjMi00NDI1LWI1NzEtMmQ2MDRmMWQ4ODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2MjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MTdkYzdiNzJmMmNmNzAyNTA3NjdlYmNiZmIzNzFlYTdmOGI5NzEzODM3NDcwMGIzYTI1ODE5MWNkNDVjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9C5hgAJGmfwFA1ac_-ibTmciD8fd0mMvQLFGZILIVOI)

Did you test if this change affects autoencoderkl?

2023-11-28 16:32 UTC, FSSRepo commented
@leejet I already checked both in img2img, and they work well with the changes I made. However, img2img is not yielding good results when modifying images. It either smoothes them too much or makes them very similar to the original, even with a strength of 0.1. I tested with previous versions of stable diffusion.cpp, and the results were exactly the same.

2023-11-28 16:32 UTC, leejet commented
> @leejet This pull request is ready for review and merge; I've tested everything, and with the latest commit, I've resolved the issue #92.

Great job! Thanks for your contributions. I'll take some time to review and merge it.

2023-11-28 16:56 UTC, FSSRepo commented
> Great job! Thanks for your contributions. I'll take some time to review and merge it.

I like this project, and I hope to be able to help until I create a server and a web interface. But for now, I want to optimize it as much as possible.

P.S.: I'll be optimizing the group norm kernel. I hope to finish it today; I already have a rough idea of what I need to do. I prefer to add it in the next pull request since it might take longer than expected to refine and test it.

2023-11-28 17:13 UTC, Green-Sky commented
> The im2col cuda kernel has been improved; it is now twice as fast, although the bottleneck still lies in the group norm kernel.

dude, this doubled my sampling speed for 512x512 from 1sec to 0.5sec :rocket: 

```
[INFO]  stable-diffusion.cpp:5469 - generating image: 1/10 - seed 819081901
[DEBUG] stable-diffusion.cpp:2409 - diffusion compute buffer size: 552.57 MB
  |==================================================| 6/6 - 1.99it/s
[INFO]  stable-diffusion.cpp:5481 - sampling completed, taking 3.04s
```

2023-11-28 21:06 UTC, FSSRepo commented
I already optimized the kernel group norm. Before, it took 500 ms for the UNet forward pass; now it only takes 5.4 ms.

2023-11-28 21:08 UTC, Amin456789 commented
this speed ups are insane! thanks for ur hard work! wish we cpu users get this speed ups too like cuda

2023-11-28 21:19 UTC, Amin456789 commented
thank u for trying! i have a question, ur first post here says cpu backend, does it mean us cpu users will get that speed up from the first post or this whole taesd implement is for cuda?

2023-11-28 21:20 UTC, FSSRepo commented
> thank u for trying! i have a question, ur first post here says cpu backend, does it mean us cpu users will get that speed up from the first post or this whole taesd implement is for cuda?

It works on both backends.

2023-11-28 22:44 UTC, Green-Sky commented
> I already optimized the kernel group norm. Before, it took 500 ms for the UNet forward pass; now it only takes 5.4 ms.
> 
> AutoEncoderKL now takes 1.3 segs in CUDA Backend

```
[INFO]  stable-diffusion.cpp:5469 - generating image: 1/1 - seed 1192558616
[DEBUG] stable-diffusion.cpp:2409 - diffusion compute buffer size: 552.57 MB
  |==================================================| 20/20 - 5.35it/s
[INFO]  stable-diffusion.cpp:5481 - sampling completed, taking 3.83s
[INFO]  stable-diffusion.cpp:5489 - generating 1 latent images completed, taking 3.83s
[INFO]  stable-diffusion.cpp:5491 - decoding 1 latents
[DEBUG] stable-diffusion.cpp:3277 - vae compute buffer size: 1664.00 MB
[DEBUG] stable-diffusion.cpp:5369 - computing vae [mode: DECODE] graph completed, taking 0.69s
[INFO]  stable-diffusion.cpp:5499 - latent 1 decoded, taking 0.69s
[INFO]  stable-diffusion.cpp:5503 - decode_first_stage completed, taking 0.69s
[INFO]  stable-diffusion.cpp:5508 - txt2img completed in 4.54s
```

o.o speed

2023-11-29 05:54 UTC, Jonathhhan commented
Yes, very fast. Here a small GUI made with `ofxImGui` and `Open Frameworks`:
![Screenshot 2023-11-29 064943](https://github.com/leejet/stable-diffusion.cpp/assets/41275844/549312df-27e9-4451-aefe-3479cfcc9dab)

2023-11-29 07:13 UTC, Amin456789 commented
@Jonathhhan that is very nice! this sd can use a gui, could u please release it in the future? it will be great to use this sd with a gui too

2023-11-29 12:38 UTC, Amin456789 commented
@FSSRepo I am so excited to use and test this now! but i don't know how to download avx2 version from this "all checked have passed" thing... could u please tell me how? plus it seems the converted doesn't work with those in release section and can't convert anything so i am stuck with using the LCM model only

Also it will be great if u upload the gguf fp16 of taesd

2023-11-29 13:18 UTC, Amin456789 commented
> > @FSSRepo I am so excited to use and test this now! but i don't know how to download avx2 version from this "all checked have passed" thing... could u please tell me how?
> 
> I don't know what you mean, does it give you that error in CMake?
> 
> > plus it seems the convert.exe doesn't work with those in release section and can't convert anything so i am stuck with using the LCM model only
> 
> I will test the release programs.
> 
> > Also it will be great if u upload the gguf fp16 of taesd
> 
> The model that I include it's the most optimal and cannot be quantized or used at a higher precision.

thank u for ur fast answer. oh i don't know anything about coding and using cmake and stuff. so i guess i better wait to leejet put the final version in the release section.

2023-11-29 13:28 UTC, Amin456789 commented
@leejet it will be great if u can upload flash attentioned and none flash versions in release section in the future for us non programmers to test if possible, flash attention seems so good in ram, thank u

2023-11-29 14:49 UTC, FSSRepo commented
@leejet I have no idea what I touched, but it seems that the quantized models now work on CUDA; before, I only got a black image.

## AutoEncoderKL

| q4_0 | q4_1 | q5_0 | q5_1 | q8_0 | f16 |
|--------------|--------------|--------------|--------------|--------------|--------------|
| ![output_q4_0](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/9e412126-c931-4b40-b448-177c8dde9e33)    | ![output_q4_1](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/c7252034-69af-4cd0-9fb8-d524145df3ac) | ![output_q5_0](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/3f021257-fdf9-47ca-9af4-546f0ebce712) | ![output_q5_1](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/028e12b7-1db7-4a79-974a-9489eacad266) | ![output_q8_0](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/a7b825d8-1b2f-41b8-aff2-d001596d9aef) | ![output_f16](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/56a9fc3a-58eb-4b2d-9fb7-7775ffd64811) |

## TAESD

| q4_0 | q4_1 | q5_0 | q5_1 | q8_0 | f16 |
|--------------|--------------|--------------|--------------|--------------|--------------|
| ![output_q4_0](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/1e6ef509-d7b0-4497-b0ad-47a4e7443ca5) | ![output_q4_1](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/bb968bb1-d998-4698-8921-e34937da2e02) | ![output_q5_0](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/e899118a-2893-4bf3-9aaa-65fe49264afd) | ![output_q5_1](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/b55c494a-4a4d-48f8-bea0-d2f992125a3c) | ![output_q8_0](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/f5e53326-1ad6-48fa-82b3-557b7aef758b) | ![output_f16](https://github.com/leejet/stable-diffusion.cpp/assets/57494570/ab8f4a60-12e2-4b00-a633-a1b13b1c9e88) |

2023-11-29 15:16 UTC, FSSRepo commented
@Amin456789 Definitely, the release section converter is failing, but this PR (Pull Request) already fixes those errors. Just wait a few days for it to be merged.

2023-11-29 15:38 UTC, Amin456789 commented
> @Amin456789 Definitely, the release section `convert` is failing, but this PR (Pull Request) already fixes those errors. Just wait a few days for it to be merged.

i converted to fp16 and it worked, i guess it is the problem with q4 or quantized ones,

anyway, i saw ur PRs and u r a genius dude, hope someday u find free time to work on SVD too.

2023-11-29 15:51 UTC, leejet commented
> @leejet I have no idea what I touched, but it seems that the quantized models now work on CUDA; before, I only got a black image. When using quantization, I did not observe a performance improvement, but it slightly reduces memory consumption.


In fact, the model quantization will only be applied to the weight of mat_mul, other parameters including the weight/bias of conv 2d will not be quantized.

2023-11-29 15:54 UTC, leejet commented
> > @leejet I have no idea what I touched, but it seems that the quantized models now work on CUDA; before, I only got a black image. When using quantization, I did not observe a performance improvement, but it slightly reduces memory consumption.
> 
> In fact, the model quantization will only be applied to the weight of mat_mul, other parameters including the weight/bias of conv 2d will not be quantized.

For vae/unet, the conv 2d operation occupies a considerable proportion.

2023-11-29 15:54 UTC, leejet commented
> @leejet it will be great if u can upload flash attentioned and none flash versions in release section in the future for us non programmers to test if possible, flash attention seems so good in ram, thank u

After merging this commit, I will add the corresponding windows release.

2023-11-29 15:56 UTC, Amin456789 commented
> > @leejet it will be great if u can upload flash attentioned and none flash versions in release section in the future for us non programmers to test if possible, flash attention seems so good in ram, thank u
> 
> After merging this commit, I will add the corresponding windows release.

thank u!

2023-11-30 21:04 UTC, FSSRepo commented
@leejet Unfortunately, it seems that I have reached the optimization limit in CUDA that I can contribute to this project. I wanted to implement the Flash Attention kernel in cuBLAS to reduce memory usage, but upon reviewing the original implementation, it requires CUTLASS, which enables very low-level operations. However, compiling this library takes 2 hours.

I was going to try to distill only the minimum to make flash attention work, but it seems impossible for me unless I had a lot of free time.

2023-12-01 11:37 UTC, Cyberhan123 commented
@FSSRepo  If possible, please update ggml to the latest version to support hipBLAS. I want to test its status in hipBlAS.

2023-12-01 12:12 UTC, leejet commented
> @leejet Unfortunately, it seems that I have reached the optimization limit in CUDA that I can contribute to this project. I wanted to implement the Flash Attention kernel in cuBLAS to reduce memory usage, but upon reviewing the original implementation, it requires CUTLASS, which enables very low-level operations. However, compiling this library takes 2 hours.
> 
> I was going to try to distill only the minimum to make flash attention library work, but it seems impossible for me unless I had a lot of free time.

You've already done an amazing job.

2023-12-03 10:41 UTC, leejet commented
@FSSRepo I've merged my latest master code and used the model loader to load the safetensors directly instead of converting to gguf files.

2023-12-03 10:45 UTC, FSSRepo commented
> @FSSRepo I've merged my latest master code and used the model loader to load the safetensors directly instead of converting to gguf files.

I don't know why some people say they have trouble converting. During your tests, was there any model that couldn't be converted?

2023-12-03 10:48 UTC, leejet commented
> > @FSSRepo I've merged my latest master code and used the model loader to load the safetensors directly instead of converting to gguf files.
> 
> I don't know why some people say they have trouble converting. During your tests, was there any model that couldn't be converted?

I've found that many models are working quite well, and I haven't encountered any that aren't supported at the moment.

2023-12-03 10:48 UTC, Green-Sky commented on .gitignore
> +<<<<<<< HEAD
@leejet I think you just made an merge oopsy (or it was @FSSRepo did not check)

2023-12-03 10:51 UTC, leejet commented on .gitignore
> +<<<<<<< HEAD
It has been deleted now.

2023-12-03 11:26 UTC, leejet commented
> although it loses the ability to quantize the model and will have to maintain models of up to 4 or 5 GB when converted, even if it was only f16, they were < 2GB (an absolutely unnecessary space expense of 3GB to maintain unnecessary tensors for the operation of sd.cpp).

You can still quantize the model during loading without consuming excessive memory. Instead of loading the entire model into memory and then quantizing it, I've implemented a method where quantization occurs only when a tensor is loaded and requires quantization.

F16 safetensors require around 2.3GB of disk space, while q4_0 ggml/gguf demands approximately 1.5GB. In practice, there isn't a substantial reduction in storage because only mat_mul weights are quantized, not conv_2d. Additionally, many people are using both sd-webui and comfyui concurrently. Adopting universal safetensors/ckpt formats make weight-sharing across different tools more convenient.

Actually, I'm planning to implement a model saver based on the current model loader code, which will fully quantize all weights into the gguf format.

2023-12-03 11:42 UTC, FSSRepo commented
Well, okay, as long as everything is simpler and more convenient. Have you tried loading the diffuser models separately?

2023-12-03 11:52 UTC, FSSRepo commented
On some occasions, I have come across models that by extension claim to be SafeTensors but when read, they are actually PyTorch checkpoints, and vice versa. It's very rare but can happen.

2023-12-03 12:03 UTC, leejet commented
> On some occasions, I have come across models that by extension claim to be SafeTensors but when read, they are actually PyTorch checkpoints, and vice versa. It's very rare but can happen.

Yes, here is a point needing improvement.

2023-12-03 12:35 UTC, leejet commented
> > Yes, here is a point needing improvement.
> 
> The converter already handled that issue by checking at the beginning (in the generic loader, load_model) whether the file was a SafeTensor, but it can also check if it's a zip file to verify if it's a checkpoint.

I've implemented it, referring to convert, with a few changes.

2023-12-03 12:43 UTC, FSSRepo commented
> I've implemented it, referring to converter, with a few changes.

Great, Sometimes, `ftell` returns -1 when the file has recently been moved to the current directory, at least that's what happens to me without any apparent reason. Therefore, it's ideal to check the size of the SafeTensor header only when the file size is greater than 0.

2023-12-03 15:42 UTC, FSSRepo commented
> I'm not sure if `fstream`'s `tellg` will have this issue like `ftell`, at least I haven't encountered that problem myself.

I will let you know once I have fixed the issue with group norm on CUDA so that you can update the ggml module.

2023-12-03 19:21 UTC, FSSRepo commented
@leejet you can update GGML to fix the bug with group norm

```bash
cd ggml
git pull
```

2023-12-04 11:30 UTC, Green-Sky requested changes

2023-12-04 11:38 UTC, Green-Sky commented
@leejet @FSSRepo loading taesd does not work anymore
```
$ sd -m models/epicphotogasm_lastUnicorn-f16.gguf --lora-model-dir models/og/sd1/ -p "<lora:lcm-lora-sdv1-5:1>a lovely cat" --sampling-method lcm --steps 4 --cfg-scale 1 --taesd ./taesd-model.gguf
[INFO]  stable-diffusion.cpp:4387 - loading model from 'models/epicphotogasm_lastUnicorn-f16.gguf'
[INFO]  model.cpp:615  - load models/epicphotogasm_lastUnicorn-f16.gguf using gguf format
[INFO]  stable-diffusion.cpp:4409 - Stable Diffusion 1.x
[INFO]  stable-diffusion.cpp:4415 - Stable Diffusion weight type: f16
[INFO]  stable-diffusion.cpp:4565 - total memory buffer size = 1877.33MB (clip 236.18MB, unet 1641.16MB, vae 0.00MB)
[INFO]  stable-diffusion.cpp:4571 - loading model from 'models/epicphotogasm_lastUnicorn-f16.gguf' completed, taking 0.60s
[INFO]  stable-diffusion.cpp:4585 - running in eps-prediction mode
[INFO]  stable-diffusion.cpp:3815 - loading taesd from './taesd-model.gguf'
[INFO]  model.cpp:615  - load ./taesd-model.gguf using gguf format
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.4.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.3.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.4.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.18.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.5.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.3.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.3.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.14.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.1.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.14.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.1.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.10.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.10.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.10.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.10.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.10.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.10.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.12.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.13.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.13.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.13.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.13.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.13.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.13.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.4.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.14.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.14.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.14.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.7.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.14.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.15.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.15.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.15.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.15.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.15.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.15.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.17.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.8.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.18.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.9.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.18.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.9.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.18.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.9.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.18.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.9.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.18.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.19.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.19.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.3.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.3.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.3.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.9.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.4.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.4.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.4.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.5.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.5.conv.0.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.5.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.5.conv.4.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.5.conv.4.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.8.conv.0.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.8.conv.2.bias' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.8.conv.2.weight' in model file
[ERROR] stable-diffusion.cpp:3848 - unknown tensor 'first_stage_model.decoder.8.c [...]

2023-12-04 11:42 UTC, FSSRepo commented
I didn't realize, even though I am directly responsible for making it work. I think now @leejet , he wants us to use the original safetensors instead the gguf.

2023-12-04 11:45 UTC, Green-Sky commented
> I didn't realize, even though I am directly responsible for making it work. I think now @leejet , he wants us to use the original safetensors instead the gguf.

while being able to use the og files is cool, it does not offer memory-mapped models (at least with ggml) and more advanced ggml quantizations. (i know @leejet talked about quantizing on the fly, but that does not mix well with memmory-mapping + results in larger files)

2023-12-04 11:48 UTC, FSSRepo commented
I'm not very familiar with how mmap works, so it's something you can't expect from me, but I'll try to get taesd working again with gguf and address your change request.

2023-12-04 13:52 UTC, FSSRepo commented
@leejet Now loading the taesd model causes conflicts because the tensors are renamed differently during preprocessing, and that shouldn't happen, only with the diffuser models.

2023-12-04 14:27 UTC, leejet commented
I'm using this one, https://huggingface.co/madebyollin/taesd/blob/main/diffusion_pytorch_model.safetensors, because this weight contains both the encoder and decoder, and it doesn't take up much storage space.

2023-12-04 14:39 UTC, FSSRepo commented
@leejet Leaving 10 MB of padding in `cal_mem_size` arbitrarily seems excessive to me.

2023-12-04 14:45 UTC, FSSRepo commented
"It's better to leave compatibility only to the safetensor that comes with everything, the first.

2023-12-04 14:47 UTC, leejet commented
OK, I'll submit it when you're done.

2023-12-04 15:11 UTC, FSSRepo commented
@leejet Try creating a function to accurately calculate the weight of LoRA parameters.

2023-12-04 15:23 UTC, Cyberhan123 commented
> @FSSRepo It would be great if you could take the time to upgrade ggml, so that I can remove my pile of cmake that supports rocm, and also I can test the support for rocm. Because of ignorance, I bought 7900xtx .I have since moved towards support Rocm's and HIP's point of no return

Although rocm is very rubbish on Windows, it is better than nothing.

2023-12-04 15:39 UTC, FSSRepo commented
@leejet Ready, you can add the final changes and test stable diffusion 2.1 again.

2023-12-04 16:10 UTC, leejet commented
> @leejet Try creating a function to accurately calculate the memory usage of LoRA parameters.

It's been fixed now.

2023-12-04 16:12 UTC, leejet commented
> @Cyberhan123 I'm waiting for my pull request that adds the necessary functions for stable diffusion to be merged into the original repository.

This pr will be merged soon, after I finish testing the necessary features, probably today or tomorrow.

2023-12-04 16:45 UTC, Cyberhan123 commented
Sorry, This may be caused by my misunderstanding of Chinese, English and Google Translate. What I mean is to merge the main branch of ggml，I need this change: https://github.com/ggerganov/ggml/pull/626

2023-12-04 16:46 UTC, Cyberhan123 commented
@FSSRepo @leejet I'm really sorry. I really need to improve my English.

2023-12-05 06:16 UTC, Jonathhhan commented
I tried the newest version and now I have the issue that `ggml_type` is not defined in `stable-diffusion.h`. Which file do I need to include for defining it? (I try to run it as a library(which was working before the update), so probably the original is working).

2023-12-05 14:00 UTC, Jonathhhan commented
And I get a warning, if the ending `.safetensors` is written in capital letters.
model.cpp:624  - unknown format v1-5-pruned-emaonly.SAFETENSORS

2023-12-05 14:34 UTC, leejet commented
Because ggml_type is currently introduced, and I was thinking about how to provide a pure c api that hides the details of ggml.

2023-12-05 14:39 UTC, leejet commented
> @leejet Later on, we will need to refactor the code to eliminate a large portion of duplicated code and make the use of the stable diffusion API more flexible. For this reason, I proposed doing something similar to what we did with llama.cpp and whisper.cpp, natively supporting a C API.

That's what I want to do.

2023-12-05 14:40 UTC, merged

2023-12-05 14:56 UTC, leejet commented
> The TAESD model needs to be in the same folder as the stable diffusion model, which was not the case before.

I didn't find this limitation, can you post your command parameters?